/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingInquiryRouteImport } from './routes/training-inquiry'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as RiskManagementRouteImport } from './routes/risk-management'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentTermsRouteImport } from './routes/payment-terms'
import { Route as IncotermsRouteImport } from './routes/incoterms'
import { Route as HsnCodeRouteImport } from './routes/hsn-code'
import { Route as GovernmentPoliciesRouteImport } from './routes/government-policies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultancyInquiryRouteImport } from './routes/consultancy-inquiry'
import { Route as ChaRouteImport } from './routes/cha'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutExportImportRouteImport } from './routes/about-export-import'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanySlugRouteImport } from './routes/company.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompanyNewRouteImport } from './routes/_authenticated/company.new'
import { Route as AuthenticatedCompanyEditRouteImport } from './routes/_authenticated/company.edit'

const TrainingInquiryRoute = TrainingInquiryRouteImport.update({
  id: '/training-inquiry',
  path: '/training-inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskManagementRoute = RiskManagementRouteImport.update({
  id: '/risk-management',
  path: '/risk-management',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentTermsRoute = PaymentTermsRouteImport.update({
  id: '/payment-terms',
  path: '/payment-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const IncotermsRoute = IncotermsRouteImport.update({
  id: '/incoterms',
  path: '/incoterms',
  getParentRoute: () => rootRouteImport,
} as any)
const HsnCodeRoute = HsnCodeRouteImport.update({
  id: '/hsn-code',
  path: '/hsn-code',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentPoliciesRoute = GovernmentPoliciesRouteImport.update({
  id: '/government-policies',
  path: '/government-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultancyInquiryRoute = ConsultancyInquiryRouteImport.update({
  id: '/consultancy-inquiry',
  path: '/consultancy-inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaRoute = ChaRouteImport.update({
  id: '/cha',
  path: '/cha',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutExportImportRoute = AboutExportImportRouteImport.update({
  id: '/about-export-import',
  path: '/about-export-import',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugRoute = CompanySlugRouteImport.update({
  id: '/company/$slug',
  path: '/company/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanyNewRoute = AuthenticatedCompanyNewRouteImport.update({
  id: '/company/new',
  path: '/company/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanyEditRoute =
  AuthenticatedCompanyEditRouteImport.update({
    id: '/company/edit',
    path: '/company/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-export-import': typeof AboutExportImportRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cha': typeof ChaRoute
  '/consultancy-inquiry': typeof ConsultancyInquiryRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/documentation': typeof DocumentationRoute
  '/faq': typeof FaqRoute
  '/government-policies': typeof GovernmentPoliciesRoute
  '/hsn-code': typeof HsnCodeRoute
  '/incoterms': typeof IncotermsRoute
  '/payment-terms': typeof PaymentTermsRoute
  '/privacy': typeof PrivacyRoute
  '/risk-management': typeof RiskManagementRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/training-inquiry': typeof TrainingInquiryRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/company/$slug': typeof CompanySlugRoute
  '/company/edit': typeof AuthenticatedCompanyEditRoute
  '/company/new': typeof AuthenticatedCompanyNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-export-import': typeof AboutExportImportRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cha': typeof ChaRoute
  '/consultancy-inquiry': typeof ConsultancyInquiryRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/documentation': typeof DocumentationRoute
  '/faq': typeof FaqRoute
  '/government-policies': typeof GovernmentPoliciesRoute
  '/hsn-code': typeof HsnCodeRoute
  '/incoterms': typeof IncotermsRoute
  '/payment-terms': typeof PaymentTermsRoute
  '/privacy': typeof PrivacyRoute
  '/risk-management': typeof RiskManagementRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/training-inquiry': typeof TrainingInquiryRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/company/$slug': typeof CompanySlugRoute
  '/company/edit': typeof AuthenticatedCompanyEditRoute
  '/company/new': typeof AuthenticatedCompanyNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/about-export-import': typeof AboutExportImportRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cha': typeof ChaRoute
  '/consultancy-inquiry': typeof ConsultancyInquiryRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/documentation': typeof DocumentationRoute
  '/faq': typeof FaqRoute
  '/government-policies': typeof GovernmentPoliciesRoute
  '/hsn-code': typeof HsnCodeRoute
  '/incoterms': typeof IncotermsRoute
  '/payment-terms': typeof PaymentTermsRoute
  '/privacy': typeof PrivacyRoute
  '/risk-management': typeof RiskManagementRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/training-inquiry': typeof TrainingInquiryRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/company/$slug': typeof CompanySlugRoute
  '/_authenticated/company/edit': typeof AuthenticatedCompanyEditRoute
  '/_authenticated/company/new': typeof AuthenticatedCompanyNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-export-import'
    | '/auth'
    | '/blog'
    | '/cha'
    | '/consultancy-inquiry'
    | '/contact'
    | '/directory'
    | '/documentation'
    | '/faq'
    | '/government-policies'
    | '/hsn-code'
    | '/incoterms'
    | '/payment-terms'
    | '/privacy'
    | '/risk-management'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
    | '/training-inquiry'
    | '/dashboard'
    | '/blog/$slug'
    | '/company/$slug'
    | '/company/edit'
    | '/company/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-export-import'
    | '/auth'
    | '/blog'
    | '/cha'
    | '/consultancy-inquiry'
    | '/contact'
    | '/directory'
    | '/documentation'
    | '/faq'
    | '/government-policies'
    | '/hsn-code'
    | '/incoterms'
    | '/payment-terms'
    | '/privacy'
    | '/risk-management'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
    | '/training-inquiry'
    | '/dashboard'
    | '/blog/$slug'
    | '/company/$slug'
    | '/company/edit'
    | '/company/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/about-export-import'
    | '/auth'
    | '/blog'
    | '/cha'
    | '/consultancy-inquiry'
    | '/contact'
    | '/directory'
    | '/documentation'
    | '/faq'
    | '/government-policies'
    | '/hsn-code'
    | '/incoterms'
    | '/payment-terms'
    | '/privacy'
    | '/risk-management'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
    | '/training-inquiry'
    | '/_authenticated/dashboard'
    | '/blog/$slug'
    | '/company/$slug'
    | '/_authenticated/company/edit'
    | '/_authenticated/company/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AboutExportImportRoute: typeof AboutExportImportRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ChaRoute: typeof ChaRoute
  ConsultancyInquiryRoute: typeof ConsultancyInquiryRoute
  ContactRoute: typeof ContactRoute
  DirectoryRoute: typeof DirectoryRoute
  DocumentationRoute: typeof DocumentationRoute
  FaqRoute: typeof FaqRoute
  GovernmentPoliciesRoute: typeof GovernmentPoliciesRoute
  HsnCodeRoute: typeof HsnCodeRoute
  IncotermsRoute: typeof IncotermsRoute
  PaymentTermsRoute: typeof PaymentTermsRoute
  PrivacyRoute: typeof PrivacyRoute
  RiskManagementRoute: typeof RiskManagementRoute
  ShippingRoute: typeof ShippingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrainingInquiryRoute: typeof TrainingInquiryRoute
  CompanySlugRoute: typeof CompanySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training-inquiry': {
      id: '/training-inquiry'
      path: '/training-inquiry'
      fullPath: '/training-inquiry'
      preLoaderRoute: typeof TrainingInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-management': {
      id: '/risk-management'
      path: '/risk-management'
      fullPath: '/risk-management'
      preLoaderRoute: typeof RiskManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-terms': {
      id: '/payment-terms'
      path: '/payment-terms'
      fullPath: '/payment-terms'
      preLoaderRoute: typeof PaymentTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incoterms': {
      id: '/incoterms'
      path: '/incoterms'
      fullPath: '/incoterms'
      preLoaderRoute: typeof IncotermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hsn-code': {
      id: '/hsn-code'
      path: '/hsn-code'
      fullPath: '/hsn-code'
      preLoaderRoute: typeof HsnCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government-policies': {
      id: '/government-policies'
      path: '/government-policies'
      fullPath: '/government-policies'
      preLoaderRoute: typeof GovernmentPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultancy-inquiry': {
      id: '/consultancy-inquiry'
      path: '/consultancy-inquiry'
      fullPath: '/consultancy-inquiry'
      preLoaderRoute: typeof ConsultancyInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cha': {
      id: '/cha'
      path: '/cha'
      fullPath: '/cha'
      preLoaderRoute: typeof ChaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-export-import': {
      id: '/about-export-import'
      path: '/about-export-import'
      fullPath: '/about-export-import'
      preLoaderRoute: typeof AboutExportImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$slug': {
      id: '/company/$slug'
      path: '/company/$slug'
      fullPath: '/company/$slug'
      preLoaderRoute: typeof CompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company/new': {
      id: '/_authenticated/company/new'
      path: '/company/new'
      fullPath: '/company/new'
      preLoaderRoute: typeof AuthenticatedCompanyNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company/edit': {
      id: '/_authenticated/company/edit'
      path: '/company/edit'
      fullPath: '/company/edit'
      preLoaderRoute: typeof AuthenticatedCompanyEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCompanyEditRoute: typeof AuthenticatedCompanyEditRoute
  AuthenticatedCompanyNewRoute: typeof AuthenticatedCompanyNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCompanyEditRoute: AuthenticatedCompanyEditRoute,
  AuthenticatedCompanyNewRoute: AuthenticatedCompanyNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AboutExportImportRoute: AboutExportImportRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ChaRoute: ChaRoute,
  ConsultancyInquiryRoute: ConsultancyInquiryRoute,
  ContactRoute: ContactRoute,
  DirectoryRoute: DirectoryRoute,
  DocumentationRoute: DocumentationRoute,
  FaqRoute: FaqRoute,
  GovernmentPoliciesRoute: GovernmentPoliciesRoute,
  HsnCodeRoute: HsnCodeRoute,
  IncotermsRoute: IncotermsRoute,
  PaymentTermsRoute: PaymentTermsRoute,
  PrivacyRoute: PrivacyRoute,
  RiskManagementRoute: RiskManagementRoute,
  ShippingRoute: ShippingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrainingInquiryRoute: TrainingInquiryRoute,
  CompanySlugRoute: CompanySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
