/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as RiskManagementRouteImport } from './routes/risk-management'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentTermsRouteImport } from './routes/payment-terms'
import { Route as IncotermsRouteImport } from './routes/incoterms'
import { Route as HsnCodeRouteImport } from './routes/hsn-code'
import { Route as GovernmentPoliciesRouteImport } from './routes/government-policies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChaRouteImport } from './routes/cha'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutExportImportRouteImport } from './routes/about-export-import'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskManagementRoute = RiskManagementRouteImport.update({
  id: '/risk-management',
  path: '/risk-management',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentTermsRoute = PaymentTermsRouteImport.update({
  id: '/payment-terms',
  path: '/payment-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const IncotermsRoute = IncotermsRouteImport.update({
  id: '/incoterms',
  path: '/incoterms',
  getParentRoute: () => rootRouteImport,
} as any)
const HsnCodeRoute = HsnCodeRouteImport.update({
  id: '/hsn-code',
  path: '/hsn-code',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentPoliciesRoute = GovernmentPoliciesRouteImport.update({
  id: '/government-policies',
  path: '/government-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaRoute = ChaRouteImport.update({
  id: '/cha',
  path: '/cha',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutExportImportRoute = AboutExportImportRouteImport.update({
  id: '/about-export-import',
  path: '/about-export-import',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-export-import': typeof AboutExportImportRoute
  '/blog': typeof BlogRoute
  '/cha': typeof ChaRoute
  '/contact': typeof ContactRoute
  '/documentation': typeof DocumentationRoute
  '/faq': typeof FaqRoute
  '/government-policies': typeof GovernmentPoliciesRoute
  '/hsn-code': typeof HsnCodeRoute
  '/incoterms': typeof IncotermsRoute
  '/payment-terms': typeof PaymentTermsRoute
  '/privacy': typeof PrivacyRoute
  '/risk-management': typeof RiskManagementRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-export-import': typeof AboutExportImportRoute
  '/blog': typeof BlogRoute
  '/cha': typeof ChaRoute
  '/contact': typeof ContactRoute
  '/documentation': typeof DocumentationRoute
  '/faq': typeof FaqRoute
  '/government-policies': typeof GovernmentPoliciesRoute
  '/hsn-code': typeof HsnCodeRoute
  '/incoterms': typeof IncotermsRoute
  '/payment-terms': typeof PaymentTermsRoute
  '/privacy': typeof PrivacyRoute
  '/risk-management': typeof RiskManagementRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-export-import': typeof AboutExportImportRoute
  '/blog': typeof BlogRoute
  '/cha': typeof ChaRoute
  '/contact': typeof ContactRoute
  '/documentation': typeof DocumentationRoute
  '/faq': typeof FaqRoute
  '/government-policies': typeof GovernmentPoliciesRoute
  '/hsn-code': typeof HsnCodeRoute
  '/incoterms': typeof IncotermsRoute
  '/payment-terms': typeof PaymentTermsRoute
  '/privacy': typeof PrivacyRoute
  '/risk-management': typeof RiskManagementRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-export-import'
    | '/blog'
    | '/cha'
    | '/contact'
    | '/documentation'
    | '/faq'
    | '/government-policies'
    | '/hsn-code'
    | '/incoterms'
    | '/payment-terms'
    | '/privacy'
    | '/risk-management'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-export-import'
    | '/blog'
    | '/cha'
    | '/contact'
    | '/documentation'
    | '/faq'
    | '/government-policies'
    | '/hsn-code'
    | '/incoterms'
    | '/payment-terms'
    | '/privacy'
    | '/risk-management'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-export-import'
    | '/blog'
    | '/cha'
    | '/contact'
    | '/documentation'
    | '/faq'
    | '/government-policies'
    | '/hsn-code'
    | '/incoterms'
    | '/payment-terms'
    | '/privacy'
    | '/risk-management'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutExportImportRoute: typeof AboutExportImportRoute
  BlogRoute: typeof BlogRoute
  ChaRoute: typeof ChaRoute
  ContactRoute: typeof ContactRoute
  DocumentationRoute: typeof DocumentationRoute
  FaqRoute: typeof FaqRoute
  GovernmentPoliciesRoute: typeof GovernmentPoliciesRoute
  HsnCodeRoute: typeof HsnCodeRoute
  IncotermsRoute: typeof IncotermsRoute
  PaymentTermsRoute: typeof PaymentTermsRoute
  PrivacyRoute: typeof PrivacyRoute
  RiskManagementRoute: typeof RiskManagementRoute
  ShippingRoute: typeof ShippingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-management': {
      id: '/risk-management'
      path: '/risk-management'
      fullPath: '/risk-management'
      preLoaderRoute: typeof RiskManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-terms': {
      id: '/payment-terms'
      path: '/payment-terms'
      fullPath: '/payment-terms'
      preLoaderRoute: typeof PaymentTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incoterms': {
      id: '/incoterms'
      path: '/incoterms'
      fullPath: '/incoterms'
      preLoaderRoute: typeof IncotermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hsn-code': {
      id: '/hsn-code'
      path: '/hsn-code'
      fullPath: '/hsn-code'
      preLoaderRoute: typeof HsnCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government-policies': {
      id: '/government-policies'
      path: '/government-policies'
      fullPath: '/government-policies'
      preLoaderRoute: typeof GovernmentPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cha': {
      id: '/cha'
      path: '/cha'
      fullPath: '/cha'
      preLoaderRoute: typeof ChaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-export-import': {
      id: '/about-export-import'
      path: '/about-export-import'
      fullPath: '/about-export-import'
      preLoaderRoute: typeof AboutExportImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutExportImportRoute: AboutExportImportRoute,
  BlogRoute: BlogRoute,
  ChaRoute: ChaRoute,
  ContactRoute: ContactRoute,
  DocumentationRoute: DocumentationRoute,
  FaqRoute: FaqRoute,
  GovernmentPoliciesRoute: GovernmentPoliciesRoute,
  HsnCodeRoute: HsnCodeRoute,
  IncotermsRoute: IncotermsRoute,
  PaymentTermsRoute: PaymentTermsRoute,
  PrivacyRoute: PrivacyRoute,
  RiskManagementRoute: RiskManagementRoute,
  ShippingRoute: ShippingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
